[app]
port = 4567 # The listening port of the server

[message]
username = "JIRA" # Override username
icon_url = "https://confluence.atlassian.com/alldoc/files/169118009/169050326/4/1260504581635/jira_logo.png" # Override icon
date_pattern = "EEE, d MMM, yyyy" # Format according to https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
date_locale = "en-US" # Defines how things like week days and month names will be represented. Expects a IETF language tag
priority_colors = true # Color attachments according to issue priority
default_color= "#205081" # Fallback color when priority is not recognized

# These options control what fields will be printed in the response messages.
print_description = false
print_assignee = true
print_status = true
print_reporter = true
print_priority = true
print_resolution = false
print_type = false
print_created = false
print_updated = false

[rocketchat]
tokens = [] # Allowed tokens. An empty array means ALL tokens are allowed.
whitelisted_users = [] # Only messages from these users are considered. An empty array accepts messages from all users (unless blacklisted).
blacklisted_users = [ "rocket.cat", "hubot" ] # No messages from these users will be considered.
whitelisted_channels = [] # Only messages from these channels are considered. An empty array accepts messages from all channels (unless blacklisted).
blacklisted_channels = [] # No messages from these channels will be considered.
