[app]
port = 4567 # The listening port of the server
max_threads = 10 # Number of concurrent threads to handle requests from Rocket.Chat and communicate with JIRA.

[message]
username = "JIRA" # Override username
icon_url = "https://confluence.atlassian.com/alldoc/files/169118009/169050326/4/1260504581635/jira_logo.png" # Override icon
date_pattern = "EEE, d MMM, yyyy" # Format according to https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
date_locale = "en-US" # Defines how things like week days and month names will be represented. Expects a IETF language tag
priority_colors = true # Color attachments according to issue priority
default_color = "#205081" # Fallback color when priority is not recognized

	# Message fields to print by default
	[message.print_default]
	description = false
	assignee = true
	status = true
	reporter = true
	priority = true
	resolution = false
	type = false
	created = false
	updated = false

	# Message fields to print for extended messages
	[message.print_extended]
	description = true
	assignee = true
	status = true
	reporter = true
	priority = true
	resolution = true
	type = true
	created = true
	updated = true

[rocketchat]
tokens = [] # Allowed tokens. An empty array means ALL tokens are allowed.
whitelisted_users = [] # Only messages from these users are considered. An empty array accepts messages from all users (unless blacklisted).
blacklisted_users = [ "rocket.cat", "hubot" ] # No messages from these users will be considered.
whitelisted_channels = [] # Only messages from these channels are considered. An empty array accepts messages from all channels (unless blacklisted).
blacklisted_channels = [] # No messages from these channels will be considered.
